# Site settings   (jekyll build --watch)
title: Todd B. Adams
email: toddbadams@msn.com
description: My personal site and blog
encoding: utf-8
name: Todd B. Adams

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
